### ISSUE TITLE
PRS - Jyothi Ceramics - Nasik

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Presales#12]
Demo preparation for Jyothi Ceramics, Nasik

**Comment by raju-kurup** [comment]
Order received for implementation

**Comment by Gana1999** [comment]
Dear Raju,
Congrats!
We win the order from Jyoti. Pl start the further action plan.

It is ONPREMISE Deployment.

The scope of implementation is as follow;
1) Sales and distribution
2) Inventory
3) Procurement
4) Manufacturing
5) Assets Management
6) Finance and accounts

a) Accommodation and food provided by Customer. Customer will pay an amt of Rs.250 per day per person for food.
b) Number of days/time sheet to be submitted to customer for food allowance
c) Allowance to be collected from customer on a weekly basis
d) Project duration 6 Months. Both the party agreed for 3 months of delay as prt of original plan.
e) There are three major milestone
       1) SDD
      2) UAT and Training
      3) Go- Live sign off
Onsite support two weeks from golive and offshore two weeks.

Wish you very all the best!!!
Thanks
Ganapathi
