### ISSUE TITLE
PRS - Nagarjuna Construction

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Presales#35]
Dear Srini,

Presentation to be created for Nagarjuna construction with Process Production cycle.  Demo is on 08-05-2019 @ 10.30am

**Comment by srinivasanbaskaran** [comment]
Dear Sir,

Draft Presentation ready & upload the Same for your persual..
Data Sheet & Wizard will upload later..

[Nagarjuna Group - v0.pptx](https://github.com/astpl1998/Presales/files/3151805/Nagarjuna.Group.-.v0.pptx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Sir,

For your reference,  Data Sheet & Sample TB attached....

[Data Sheet.xlsx](https://github.com/astpl1998/Presales/files/3155879/Data.Sheet.xlsx)
[ASHISH__70191832_41876aff-5cac-41f1-84c1-f9b11bfc920f.pdf](https://github.com/astpl1998/Presales/files/3155880/ASHISH__70191832_41876aff-5cac-41f1-84c1-f9b11bfc920f.pdf)

**Comment by srinivasanbaskaran** [comment]
Online demo given to Sathish & Sudhakar from Nagarjuna Group.

**Comment by srinivasanbaskaran** [comment]
Dear Ganapathi Sir,

Herewith I have attached latest Presentation.

[Nagarjuna Group - v1.pptx](https://github.com/astpl1998/Presales/files/3156546/Nagarjuna.Group.-.v1.pptx)

**Comment by srinivasanbaskaran** [comment]
Demo Completed.

Proposal submitted. Awaiting Confirmation..

**Comment by raju-kurup** [comment]
Lead was closed, so closing this ticket
