### ISSUE TITLE
PRS - VARSHA MULTI TECH GROUPS

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Presales#38]
Team,

Prepare the presentation for VMT Groups with below details

1. Process Production
2. Supply Chain
3. Quality Mgnt
4. Finance

**Comment by srinivasanbaskaran** [comment]
![ST Flow](https://user-images.githubusercontent.com/46194039/58455453-60e42d00-813f-11e9-8253-3847ba130e2b.JPEG)
![Suressh sir - Notes_1](https://user-images.githubusercontent.com/46194039/58455454-60e42d00-813f-11e9-8bc7-28d97cf55d75.JPEG)
![Suressh sir - Notes_2](https://user-images.githubusercontent.com/46194039/58455456-617cc380-813f-11e9-9f6f-32c82fedff70.JPEG)
![Suressh sir - Notes_3](https://user-images.githubusercontent.com/46194039/58455457-617cc380-813f-11e9-8956-5f8299e7f538.JPEG)

**Comment by astpl1998** [comment]
Attaching the Requirement File
[VarshaRequirementStudy.xlsx](https://github.com/astpl1998/Presales/files/3226037/VarshaRequirementStudy.xlsx)

**Comment by srinivasanbaskaran** [comment]
Ganapathi Sir,

Herewith I have attached the Presentation & Data Sheet for VMT groups

Presentation:  [Varsha Multi Tech - V1.pptx](https://github.com/astpl1998/Presales/files/3364423/Varsha.Multi.Tech.-.V1.pptx)

Data Sheet: [Data Sheet-Updated.xlsx](https://github.com/astpl1998/Presales/files/3364430/Data.Sheet-Updated.xlsx)

Regards,

Srinivasan Baskaran

**Comment by Gana1999** [comment]
Pl share the list of template/forms collected from Varsha.

**Comment by astpl1998** [comment]
[VarshaDocs.zip](https://github.com/astpl1998/Presales/files/3955882/VarshaDocs.zip)

Varsha Douments uploaded

**Comment by astpl1998** [comment]
[VarshaDoc.zip](https://github.com/astpl1998/Presales/files/3959143/VarshaDoc.zip)
[VarshaDoc1.zip](https://github.com/astpl1998/Presales/files/3959144/VarshaDoc1.zip)

Varsha clatest Doc Uploaded

**Comment by raju-kurup** [comment]
Lead was closed, so closing this ticket
