### ISSUE TITLE
PRS - SMART WORKS

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Presales#39]

**Comment by srinivasanbaskaran** [comment]
Online demo given to Nitiraj from Smart Works.

Below are the some of the points are discussed.

1. Full Suite with below modules
       * Sales with CRM
       * Procurement 
       * Inventory 
       * Project Mgnt
       * Finance
       * FAM
       * EAM
       * ERM
2. Need to submit the proposal as early as possible to Client

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Lead was closed, so closing this ticket
