### ISSUE TITLE
PRS - COCONICS PVT LTD

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Presales#40]
Modeling to be prepared as well as Data Sheet & Wizards to be created in COE5 server

Data Template to be prepared for the below modules & send to UST Global

Scenario to UST Global
1. Purchase To Pay
2. Sales To Invoice 
3. Discrete Production

**Comment by astpl1998** [comment]
Template required to collect data for below scenarios. 

 

With the data Live transactions to be done in front of customer

 

Regards

Suressh.CG                      



Head - ERP Practice

Certifications: Certified RamcoERP Consultant- (Finance, Supplychain, Production, Enterprise Asset Management)

AmitySoft Technologies Pvt Ltd.,

Email:  <mailto:sharmilabk@amitysoft.in> suressh@amitysoft.com | Mobile: +91-9790789979

Telephone :+91-044 42035577 / 24328077

Skype: suressh.cg LinkedIn: suressh@amitysoft.com <mailto:suressh@amitysoft.com>  Twitter : @suresshcg

HO: 6/22,II Floor, Dhandapani Street, T.Nagar, Chennai - 600 017, India

Offices : Bangalore, Mumbai, Vadodara, Kochi.

 <http://www.amitysoft.com/> www.amitysoft.com

Enterprise Solutions: ERP, Data Analytics, IoT

Advisory & Technical Services: Enterprise Cyber Security, Quality Assurance & Testing,

Functional Sizing, CMMI/ISO

Training: Testing, Software Quality Management, Big Data, Info Security, ERP

Disclaimer: The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorized. If you have received this communication in error, please address with the subject heading "Received in error," send to info@amitysoft.com <mailto:info@amitysoft.com> , then delete the e-mail and destroy any copies of it. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any opinions or advice contained in this e-mail are subject to the terms and conditions expressed in the governing agreement between Amitysoft and the client. Opinions, conclusions and other information in this e-mail and any attachments that do not relate to the official business of Amitysoft Technologies are neither given nor endorsed by it.

 

Amitysoft Technologies cannot guarantee that the e-mail communications are secure or error-free, as information could be intercepted, corrupted, amended, lost, destroyed, arrive late or incomplete, or contain viruses.

**Comment by srinivasanbaskaran** [comment]
Dear Sir,

Please find the Data Template for COCONICS.


[Data Tempate_COCONICS.xlsx](https://github.com/astpl1998/Presales/files/3508937/Data.Tempate_COCONICS.xlsx)
