### ISSUE TITLE
PRS - SEIMENS

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Presales#41]
Presentation to be prepared

**Comment by astpl1998** [comment]
Initial Demo completed, understanding doc attached
Customer need Quote
Customer would like to have a detailed demo next week 
[Siemens-Understanding for Data Modelling.xlsx](https://github.com/astpl1998/Presales/files/3495632/Siemens-Understanding.for.Data.Modelling.xlsx)

**Comment by raju-kurup** [comment]
Lead was closed, so closing this ticket
