### ISSUE TITLE
PRS - Swathi Engineering - Chennai

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Presales#6]
Prepare the product demo for Swathi Engineering.  Details of the customer is attached and website address is also mentioned.

http://www.swathiengineering.com/
[Requirement-Swathi Engineering.xlsx](https://github.com/astpl1998/Support/files/2859920/Requirement-Swathi.Engineering.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dropped....
