### ISSUE TITLE
PRS - Pinax Group - Kolkata and Patna

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Presales#9]
Dear Srini,

Prepare demo script for pinax steel and pinax paper mills.

https://pinaxsteels.com/
[pinax - work flow.xlsx](https://github.com/astpl1998/Presales/files/3033752/pinax.-.work.flow.xlsx)
[Pinax Steel PROCESS FLOW CHART.PDF](https://github.com/astpl1998/Presales/files/3033753/Pinax.Steel.PROCESS.FLOW.CHART.PDF)
[Copy of pinax steel - work flow (00000003).xlsx](https://github.com/astpl1998/Presales/files/3033766/Copy.of.pinax.steel.-.work.flow.00000003.xlsx)

**Comment by srinivasanbaskaran** [comment]
Hi Praba,

Please prepare a demo script for the Pinax Steel & Paper Mils...

**Comment by raju-kurup** [comment]
Hi Srini,

Online demo given to Mr. Mittal.  So please close this issue

**Comment by srinivasanbaskaran** [comment]
Online demo given to Customer...
